"""create tables

Revision ID: 9058b93e4641
Revises: 7e3c78d4d937
Create Date: 2026-01-05 07:36:06.098967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9058b93e4641'
down_revision: Union[str, Sequence[str], None] = '7e3c78d4d937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='문서 ID'),
    sa.Column('domain', sa.Enum('CS', 'DEV', name='domain'), nullable=False, comment='문서 도메인'),
    sa.Column('source_type', sa.Enum('GITHUB', 'SLACK', 'NOTION', 'RAW_TEXT', 'FILE', name='sourcetype'), nullable=False, comment='문서 출처 유형'),
    sa.Column('source_id', sa.String(length=255), nullable=False, comment='출처에서 제공하는 문서 ID'),
    sa.Column('title', sa.String(length=512), nullable=True, comment='문서 제목'),
    sa.Column('raw_content', sa.Text(), nullable=True, comment='문서 내용'),
    sa.Column('raw_content_gz', sa.LargeBinary(), nullable=False, comment='압축된 문서 내용'),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='문서 내용 해시'),
    sa.Column('version', sa.Integer(), nullable=False, comment='문서 버전'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', name='u_idx_source_type_source_id')
    )
    op.create_table('query_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='쿼리 로그 ID'),
    sa.Column('query_text', sa.Text(), nullable=False, comment='사용자 쿼리 텍스트'),
    sa.Column('topk', sa.Integer(), nullable=False, comment='검색된 청크 개수'),
    sa.Column('selected_chunk_ids', sa.JSON(), nullable=True, comment='선택된 청크 ID들 (JSON 직렬화된 형태)'),
    sa.Column('expended_chunk_ids', sa.JSON(), nullable=True, comment='확장된 청크 ID들 (JSON 직렬화된 형태)'),
    sa.Column('answer', sa.Text(), nullable=True, comment='생성된 답변 텍스트'),
    sa.Column('input_tokens', sa.Integer(), nullable=True, comment='입력 토큰 수'),
    sa.Column('output_tokens', sa.Integer(), nullable=True, comment='출력 토큰 수'),
    sa.Column('total_tokens', sa.Integer(), nullable=True, comment='총 토큰 수'),
    sa.Column('meta', sa.JSON(), nullable=True, comment='메타데이터'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='청크 ID'),
    sa.Column('document_id', sa.Integer(), nullable=False, comment='FK: Document.id, 관련 문서 ID'),
    sa.Column('context_id', sa.Integer(), nullable=False, comment='청크가 속한 컨텍스트 ID'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='문서 내 청크 인덱스'),
    sa.Column('chunk_text', sa.Text(), nullable=False, comment='청크 텍스트 내용'),
    sa.Column('chunk_hash', sa.String(length=64), nullable=False, comment='청크 내용 해시'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk')
    op.drop_table('query_log')
    op.drop_table('document')
    # ### end Alembic commands ###
